logging:
  level:
    root: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:${user.home}/wechat_ticket.db
    username: sa
    password: 
    driver-class-name: org.h2.Driver 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

security:
   basic:
      enabled: false